[utils/mapedit] Disable precompiled header
This causes error C1010, because the base_tool.qpc compiles several .cpp
files that do not #include cbase.h. An Alternative solution is to use
source_dll_base.qpc directly, and not compile those files in mapedit.